<?php

/**
 * @file
 * Primary module hooks for GT People module.
 */

/**
 * Allows the text_textarea widget to be used by the text field.
 * From: https://www.drupal.org/project/textarea_widget_for_text
 */

/**
 * Implements hook_field_widget_info_alter().
 */
function gt_people_field_widget_info_alter(array &$info) {
  $info['text_textarea']['field_types'][] = 'text';
  $info['string_textarea']['field_types'][] = 'string';
}

